### ISSUE TITLE
Awesome Library!

### ISSUE THREAD

**Issue by NicholasBellucci** [johnpatrickmorgan/NavigationBackport#1]
Just wanted to say this library works like a charm! Awesome stuff! One question I had was would you be able to provide a little more clarity around the below implementation? Maybe with an example in the demo app? Just trying to better wrap my head around what needs to be done. Again nice job with everything!

```swift
$path.withDelaysIfUnsupported {
  $0.append(Screen.orders)
  $0.append(Screen.editOrder(id: id))
  $0.append(Screen.confirmChanges(orderId: id))
}
```

**Comment by johnpatrickmorgan** [comment]
Thanks so much for your kind words, I'm glad it's helpful!

I've attempted to better explain the use of `withDelaysIfUnsupported` in the [README](https://github.com/johnpatrickmorgan/NavigationBackport#deep-linking) and in the [example app](https://github.com/johnpatrickmorgan/NavigationBackport/blob/242ed035c9ffd199a70aeeb09fd204a19aafd8f4/NavigationBackportApp/Shared/ContentView.swift#L22-L39).

**Comment by NicholasBellucci** [comment]
Awesome thank you!
