### ISSUE TITLE
NBNavigationLink missing `public init(@ViewBuilder destination: () -> Destination, @ViewBuilder label: () -> Label)` initializer

### ISSUE THREAD

**Issue by theedov** [johnpatrickmorgan/NavigationBackport#12]
Would be nice to have NBNavigationLink support a simple push so we don't have to switch between `NBNavigationLink` and `NavigationLink`:

```
NBNavigationLink {
    DestinationView()
} label: {
    LabelView()
}
```

NavigationLink:
```
@available(iOS 13.0, macOS 10.15, tvOS 13.0, watchOS 6.0, *)
public struct NavigationLink<Label, Destination> : View where Label : View, Destination : View {

    /// Creates a navigation link that presents the destination view.
    /// - Parameters:
    ///   - destination: A view for the navigation link to present.
    ///   - label: A view builder to produce a label describing the `destination`
    ///    to present.
    public init(@ViewBuilder destination: () -> Destination, @ViewBuilder label: () -> Label)

    ...
}
```

**Comment by DragonCherry** [comment]
NBNavigationLink is designed to mapped to an object, each objects configures path, which is an array of AnyHashable objects that handled & held by NBNavigationStack. If you want to create a NBNavigationLink without corresponding 'AnyHashable' object, you have to create a NBNavigationLink with some empty & hashable type object without data in it.

**Comment by johnpatrickmorgan** [comment]
Thanks for raising this issue @theedov. I can see how it might be desirable to include this API for completeness, but doing so would require some abstraction and complication that I don't think is worthwhile, and I think it's better to use NavigationLink directly for those purposes.
