### ISSUE TITLE
`cast from 'Codable' (aka 'Decodable & Encodable') to unrelated type 'AnyHashable' always fails`

### ISSUE THREAD

**Issue by theedov** [johnpatrickmorgan/NavigationBackport#13]
Getting some type casting warnings.

<img width="1097" alt="Screen Shot 2022-08-08 at 2 46 06 pm" src="https://user-images.githubusercontent.com/30866972/183341324-787c1480-c8bf-42bf-b504-7c65cdb29cfb.png">

**Comment by johnpatrickmorgan** [comment]
Thanks for raising this @theedov! The cast won't always fail, thanks to the compiler magic around `AnyHashable`, but
it seems the compiler code that gives the warning doesn't seem to recognise that. I've avoided the warning by casting to Any first, and will try to file a Radar for the incorrect warning. The warning should no longer appear in v0.3.2.
