### ISSUE TITLE
Missing `Equatable` conformance

### ISSUE THREAD

**Issue by kielgillard** [johnpatrickmorgan/NavigationBackport#15]
Hey there, thanks for the awesome library!

SwiftUI's `NavigationPath` is [documented](https://developer.apple.com/documentation/swiftui/navigationpath) as `Equatable` but the backport's `NavigationPath` is only `Hashable`. 

Any chance the backport's path could be made Equatable? Or does the SwiftUI interface tell the documentation wrong?

**Comment by kielgillard** [comment]
I can see `NavigationPath` is `Equatable` in Xcode Version 14.0 beta 5 (14A5294e) and later.

**Comment by johnpatrickmorgan** [comment]
Thanks @kielgillard, your PR #16 is now merged.
