### ISSUE TITLE
NavigationPath Codable

### ISSUE THREAD

**Issue by NicholasBellucci** [johnpatrickmorgan/NavigationBackport#2]
Hey so I have been messing around with trying to make NavigationPath Codable in the meantime. Curious if you have any ideas on how maybe it is getting done? Wanted to try and implement something rudimentary in the time being.

**Comment by johnpatrickmorgan** [comment]
HI @NicholasBellucci, thanks for giving the problem your attention. I haven’t had a chance to tackle this properly so far, but here are my initial thoughts.  

It would be tough to exactly replicate the API of `NavigationPath`. I think _encoding_ the path’s elements is straightforward: assuming the type conforms to `Codable`, we can ask it to encode itself, and also encode its type as a String. That seems to be what `NavigationStack.CodableRepresentation` is doing - it outputs something like:

```
[
"NavigationBackportApp.EmojiVisualisation",
"{\"emoji\":\"🎈\",\"count\":99}",
"Swift.Int",
"99"
]
```

The trouble comes when trying to _decode_ that into instances of the correct types. I believe doing so with just that data would be impossible in Swift, as there’s no way to get a reference to a Swift type from a String (e.g. there’s no equivalent to Objective-C's `NSClassFromString` in Swift). 

One option would be to require the user to also pass in references to any types that the representation might contain when initialising the `NavigationPath`, e.g.  by adding a `types` argument to this API:

```swift
extension NBNavigationPath {
	init(_ codable: NavigationPath.CodableRepresentation, types: [Codable.Type]) { … }
```

That should allow any of those types to be instantiated. It might even be possible to populate the types automatically by bubbling up the types provided in calls to `nbNavigationDestination`. But that info would not be available at the moment of initialisation, so it would have to be lazily evaluated.

**Comment by iOSBrett** [comment]
Have you guys seen this article from PointFree, I think it may help you.

https://www.pointfree.co/blog/posts/78-reverse-engineering-swiftui-s-navigationpath-codability

**Comment by johnpatrickmorgan** [comment]
@iOSBrett Thanks, yes I was very happy to see that blog post. I tried it out on the [feature/codable](https://github.com/johnpatrickmorgan/NavigationBackport/tree/feature/codable) branch, though I was getting a segfault from the use of `_openExistential` in Swift < 5.7. I haven't yet overcome that, but it works great on Swift 5.7 and above.

**Comment by johnpatrickmorgan** [comment]
I eventually realised that the set fault was happening because you can't pass a closure to `_openExistential`, only a function. The next hurdle was to convince the compiler that the decoded element was indeed `Hashable`, so that it could be added to `NBNavigationPath`'s `var elements: [AnyHashable]`. I overcame that by using `[Any]` in `NBNavigationPath` instead. So the branch should now work as expected (for iOS 14 and above at least). 

Eventually, rather than failing if `_typeByName` fails, we could box the undecoded Data and type name in a struct, and wait for the DestinationBuilder to decode it, by attempting decoding with each of the types it knows about.

**Comment by johnpatrickmorgan** [comment]
This has been added in [v0.3.0](https://github.com/johnpatrickmorgan/NavigationBackport/releases/tag/0.3.0).
