### ISSUE TITLE
Warning when using with @Published values

### ISSUE THREAD

**Issue by denizdogan** [johnpatrickmorgan/NavigationBackport#24]
When using this library with @Published values, I get the old familiar warning in Xcode:

>Publishing changes from background threads is not allowed; make sure to publish values from the main thread (via operators like receive(on:)) on model updates.

Note that this warning actually stems from `Binding.withDelaysIfUnsupported(from:to:keyPath:)` in the NavigationBackport source code, and not from my app source code.

Is this something that I should be worried about? Is it "just a warning"? Can we get rid of it by making some changes to the NavigationBackport library?

Related to #20

**Comment by johnpatrickmorgan** [comment]
Thanks @denizdogan for raising this issue. I believe I've fixed it by correcting the missing `@MainActor` annotation on one of the `withDelaysIfUnsupported` methods. This is available in v0.6.1.

**Comment by denizdogan** [comment]
@johnpatrickmorgan Sorry, didn't mean to leave you hanging, I honestly literally _just_ had time to test the fix, and everything seems good. Thanks for your help!

**Comment by johnpatrickmorgan** [comment]
No worries, thanks for confirming!
