### ISSUE TITLE
View pushed with inset when using dismiss Environment variable

### ISSUE THREAD

**Issue by houtzager** [johnpatrickmorgan/NavigationBackport#25]
Hey,

First of thanks for the lib as I do really like having my app's navigation structure prepared for SwiftUI 4 and up. :)

Ever since iOS 16.1, I noticed an issue causing a non spinning loading indicator to show directly after pushing a view inside an NBNavigationStack. It seems to be related with having a `@Environment(\.dismiss) var` within the pushed view, as with a non-refreshable list, you also see the list being pulled down upon push (which would with a refreshable list show the spinner).

| With refresh | Without refresh |
|---|---|
| ![simulator_screenshot_4DCAE72C-930F-43B3-89A6-10189A9EF9BE](https://user-images.githubusercontent.com/1859059/198378892-3c174c93-8d49-4242-949c-6f8119f83551.png) | ![simulator_screenshot_B869F423-39D4-4012-AB21-40A97F703EC7](https://user-images.githubusercontent.com/1859059/198378205-af0be03d-69a4-4202-9721-be197519b075.png) |

Note this issue has been occurring on iOS 16.1 devices, even though the app was build with Xcode 14.0.1. Replicating the issue on simulator I managed to do from the Xcode 14.1 RC 2. 

I added some replication code below to debug this issue and hope someone can help me with this. 

```swift
 import NavigationBackport

 @main
 struct SomeApp: App {
     
     var body: some Scene {
         WindowGroup {
             TestView()
         }
     }
 }

class TestSubViewModel: ObservableObject {
    
    @Published var sections: [String] = ["Test 1", "Test 2"]
    @Published var shouldDismiss = false

}
struct TestSubView: View {
    
    @ObservedObject var viewModel: TestSubViewModel
    @Environment(\.dismiss) var dismiss
    
    var body: some View {
        let _ = self._printingChanges()
        List {
            ForEach(viewModel.sections, id: \.self) { section in
                Section {
                    Text(section)
                } header: {
                    Text("Header")
                }
            }
        }
        .refreshable {
        }
        .onChange(of: viewModel.shouldDismiss, perform: { shouldDismiss in
            if shouldDismiss {
                dismiss()
            }
        })
        .navigationBarTitleDisplayMode(.inline)
        .navigationTitle("Row")
    }
}

struct TestView: View {
        
    var body: some View {
        NBNavigationStack {
         List {
             ForEach(1..<10) { row in
                 NBNavigationLink("Row \(row)", value: row)
             }
         }
         .nbNavigationDestination(for: Int.self, destination: { row in
             TestSubView(viewModel: .init())
         })
         .refreshable {}
         .navigationTitle("Refresh Indicator Bug")
       }
    }
}
```

**Comment by johnpatrickmorgan** [comment]
Thanks @houtzager - that's strange, I don't know why the `dismiss` environment value would trigger that behaviour. It feels like a SwiftUI bug. 

Fortunately, you can use the new `PathNavigator` environment object instead, which doesn't have this problem.

```swift
@EnvironmentObject var navigator: PathNavigator
```

So you can use `navigator.pop()` instead of `dismiss()`.

**Comment by houtzager** [comment]
Hey @johnpatrickmorgan, thanks for the quick response!

I can confirm that using the PathNavigator from 0.6 indeed resolves the issue.
