### ISSUE TITLE
No ObservableObject of type DestinationBuilderHolder found.

### ISSUE THREAD

**Issue by raduncicen** [johnpatrickmorgan/NavigationBackport#26]
![Screen Shot 2022-10-29 at 16 12 06](https://user-images.githubusercontent.com/44670959/198833425-268c684f-a118-43eb-a843-05f30edd8928.png)

Hello!
I keep get this error when i try to navigate.

Fatal error: No ObservableObject of type DestinationBuilderHolder found. A View.environmentObject(_:) for DestinationBuilderHolder may be missing as an ancestor of this view.

Couldn't really figured out why it crashes since a default environment object is presented inside NBNavigationStack.
Do you have any suggestion on how to solve this. Sorry if it's already too obvious 😅

**Comment by johnpatrickmorgan** [comment]
Thanks @raduncicen ! Is this on the latest version (0.6.1) of `NavigationBackport`? I did make a change to how these environment objects were propagated so perhaps I overlooked something. Do you see the  crash on all versions of iOS? And what change are you making to the path that triggers this crash please? Thanks a lot.

**Comment by johnpatrickmorgan** [comment]
@raduncicen I haven't been able to reproduce this so any pointers on how you're using the library would be great too, thanks!

**Comment by raduncicen** [comment]
@johnpatrickmorgan Sorry for the late response 🙏 
In the end the problem was not due to this library.
It took quite some time for me to resolve it but apparently it was due to the modularization that I've implemented on my project. I guess It's an Xcode bug, but on real device it confuses the location of the framework due to the modularization i've implemented.

**Comment by mp205** [comment]
Hi @raduncicen , I am having the same issue - probably also due to modularization. Could you please share how did you solve it? Thanks

**Comment by raduncicen** [comment]
Hi @mp205, It has been quite a long time so I cannot remember it clearly. What type of modularization are you using? And are you using cocoapods?

**Comment by aehlke** [comment]
@mp205 did you solve it?
