### ISSUE TITLE
Reset navigation path

### ISSUE THREAD

**Issue by rifqifadh** [johnpatrickmorgan/NavigationBackport#30]
Hello!
I get this instant pop-back on the last view when trying to reset the navigation path.

[Sample Code](https://gist.github.com/rifqifadh/afa301ea1a9dcbfcf817c751939bfc30)
![Simulator Screen Recording - iPhone 14 Pro - 2023-01-26 at 21 14 50](https://user-images.githubusercontent.com/38750970/214858162-fc044f94-a2cb-4126-9957-a71ae8a2f518.gif)

**Comment by johnpatrickmorgan** [comment]
Thanks for raising this issue @rifqifadh! 

I think [this change](https://github.com/johnpatrickmorgan/NavigationBackport/compare/bugfix/issue-30) fixes this issue, but I'd like to take some time to check that it doesn't cause any other issues before merging.

Note though, that when replacing the stack of screens with a new stack, the animation seen will be dictated by the difference in screen count between the new and old stacks:

- If the new stack is smaller, there will be a pop animation.
- If the new stack is one larger, there will be a push animation.
- If the new stack is the same length (as in your case), there will be no animation.
- If the new stack is more than one larger, you should wrap the mutation in a `withDelaysIfUnsupported` call to ensure SwiftUI reflects the new screen stack in the UI. This overcomes a limitation of `NavigationView`.

**Comment by johnpatrickmorgan** [comment]
I've now merged this fix in v0.7.1, as I don't see any regressions. Thanks for raising this issue @rifqifadh.
