### ISSUE TITLE
Initial Path is not resolved.

### ISSUE THREAD

**Issue by connor-ricks** [johnpatrickmorgan/NavigationBackport#32]
If my path has an initial value, it is not executed. This prevents enabling capabilities link deep linking or pre-hydrating navigational flows.

Example...

```swift

/// Properties
@State var path: [String] = ["Hydrated"]

/// Body
NBNavigationStack(path: $path) {
    VStack {
        Text("Root")
    }
    .nbNavigationDestination(for: String.self) { string in
        Text(string)
    }
}
```

In the above example, the navigation stack won't push "Hydrated"

**Comment by johnpatrickmorgan** [comment]
Thanks for raising this issue. I've made some changes to better support this use case in v0.7.3. It is now possible to start with non-zero path counts and your example should work as expected. Note though that starting with more than one path element will mean push animations are shown, as `NavigationView` does not support starting with more than one pushed screen.
