### ISSUE TITLE
"Fatal error: No view builder found for type <type>" when presenting the screen in the traditional UIKit way 

### ISSUE THREAD

**Issue by mshibanami** [johnpatrickmorgan/NavigationBackport#43]
Hi,
I'm using NavigationBackport 0.9.0 in the following manner:

```swift
UIApplication.shared.delegate?.window??.rootViewController?
    .present(UIHostingController(
        rootView: NBNavigationStack(path: .constant([1, 2, 3])) {
            Text("Hello")
                .nbNavigationDestination(for: Int.self) {
                    Text("\($0)")
                }
        }))
```

But when I run it on iOS 16, the app reaches this `assertionFailure()`:

![Screenshot 2023-09-13 at 4 12 27 pm](https://github.com/johnpatrickmorgan/NavigationBackport/assets/1333214/64b97d91-086a-4e28-bd1f-765ccbf0a9d7)

I've confirmed this occurs on both a physical device (16.6.1) and a simulator (16.4), but this didn't happen on iOS 17 simulator.
Is this expected?

Thank you so much for maintaining this great package!

**Comment by johnpatrickmorgan** [comment]
Hi @mshibanami! Thanks for raising this issue. I have not had much time to investigate but I was able to reproduce the issue. There does seem to be some strange behaviour with environment objects when hosting SwiftUI views in a UIKit host. Bizarrely, I found that including a Button in the root view of the navigation stack resolved the issue, e.g.:

```swift
      .present(UIHostingController(
        rootView: NBNavigationStack(path: .constant([1, 2, 3])) {
          Text("Hello")
            .background(Button("") {}.hidden()) // including this line prevents the crash!?
            .nbNavigationDestination(for: Int.self) {
              Text("\($0)")
            }
        }), animated: true)
```

I'll investigate further but wanted to document that oddity in the meantime.

**Comment by mshibanami** [comment]
@johnpatrickmorgan Oh, that's interesting. It also suppresses the assertion failure for me. Thanks!
Personally, I'm already happy with this workaround, so please feel free to close this card whenever you want.
