### ISSUE TITLE
Xcode warnings in Binding+withDelaysIfUnsupported.swift

### ISSUE THREAD

**Issue by ingopaulsen** [johnpatrickmorgan/NavigationBackport#45]
**Describe the bug**
I have received the following warning in Xcode for NavigationBackport package:

`Binding+withDelaysIfUnsupported.swift`:

- Capture of 'self' with non-sendable type 'Binding<Array<Screen>>' in a `@Sendable` closure
- Capture of 'self' with non-sendable type 'Binding<NBNavigationPath>' in a `@Sendable` closure

**Environment (please complete the following information):**
 - Xcode version: Xcode 15.0
 - NavigationBackport Version: v0.9.0
 - Device: iPhone7
 - Simulator: iPhone15
 - OS: iOS 15+

**Comment by johnpatrickmorgan** [comment]
Thanks @ingopaulsen  - I've added some missing `@MainActor` annotations in v0.9.1, which should resolve this issue.
