### ISSUE TITLE
On iOS 18 (beta), navigating back from a nested detail view causes the NavigationStack to pop to the root

### ISSUE THREAD

**Issue by timlittlelabs** [johnpatrickmorgan/NavigationBackport#54]
When using:

`        NBNavigationStack(path: router.navigationPath) {
            content
                .nbNavigationDestination(for: MainRouteDestination.self) { destination in
                    router
                        .view(destination: destination, route: .navigation)
                        .navigationBarBackButtonHidden(!router.backNavigationEnabled)
                }
        }
        .nbUseNavigationStack(.whenAvailable)`

On the iOS 18 beta, when navigating back from a nested detail view (not one but two levels deep), pressing back or using the back gesture takes the user back to the root view. It seems that the navigation path is fully popped.

When using `.nbUseNavigationStack(.never)` this doesn't occur.

Note: This doesn't occur on the simulator, only on real devices

**Comment by johnpatrickmorgan** [comment]
Thanks for raising this @timlittlelabs - I'll have a look into it.

**Comment by johnpatrickmorgan** [comment]
Hi @timlittlelabs - sorry, I'm having difficulty reproducing this issue. I'm using the Xcode 16.1 beta, running an iOS 18.1 simulator, and testing using the example app in this repo, but I haven't seen any issues. Are you able to provide a minimal reproduction please?

**Comment by timlittlelabs** [comment]
@johnpatrickmorgan Sorry for the false alarm. In the end I was able to fix this, it was a strange culmination of circumstances on our end where keeping the navigation state in our top-most level view was messing up the navigation path (in combination with a TabView). Closing this as resolved.

By the way, thanks for maintaining this library, it has been a huge help!

**Comment by johnpatrickmorgan** [comment]
Glad it's sorted, thanks @timlittlelabs!
