### ISSUE TITLE
A navigationDestination was declared earlier on the stack

### ISSUE THREAD

**Issue by cosmograve** [johnpatrickmorgan/NavigationBackport#58]
On start of my app I have alert "A navigationDestination for “Swift.AnyHashable” was declared earlier on the stack. Only the destination declared closest to the root view of the stack will be used."

import SwiftUI
import NavigationBackport

@main
struct MyApp: App {
    @State var path = NBNavigationPath()
    var body: some Scene {
        WindowGroup {
            NBNavigationStack(path: $path) {
                ContentView()
            }
        }
    }
}

**Comment by johnpatrickmorgan** [comment]
Thanks for raising this. You should no longer see this warning after v0.11.2, which was just released.
