### ISSUE TITLE
Cocoa pods update

### ISSUE THREAD

**Issue by vveidi** [johnpatrickmorgan/NavigationBackport#59]
Hi! Currently, 0.9.3 is the latest version you can download on CocoaPods. However, there are some bugs there and 0.11.1 seems to be the latest version available right now. Will the podspec be updated in the near future?

Thanks for the great library anyway

**Comment by johnpatrickmorgan** [comment]
Thanks for the reminder @vveidi, I've just published v0.11.1 to CocoaPods.

**Comment by velvetk** [comment]
Hi @johnpatrickmorgan,

I would really appreciate it if you could publish the new version v0.11.4 to CocoaPods. Thanks
